import { MailerService } from '@nestjs-modules/mailer';
import { Injectable } from '@nestjs/common';
import { UsersResponse } from 'src/model/users.model';

@Injectable()
export class MailService {
  constructor(private mailerService: MailerService) {}

  async sendResetPassEmail(user: UsersResponse, token: string) {
    const url: string = `${process.env.FRONTEND_URL}/reset-password?token=${token}`;
    const bodyEmail: string = `<!doctype html><html ⚡4email data-css-strict><head><meta charset="utf-8"><style amp4email-boilerplate>body{visibility:hidden}</style><script async src="https://cdn.ampproject.org/v0.js"></script><style amp-custom>u + .body img ~ div div { display:none;}span.MsoHyperlink, span.MsoHyperlinkFollowed { color:inherit;}a.es-button { text-decoration:none;}.es-desk-hidden { display:none; float:left; overflow:hidden; width:0; max-height:0; line-height:0;}.es-button-border:hover { border-color:#3D5CA3 #3D5CA3 #3D5CA3 #3D5CA3; background:#FFFFFF;}.es-button-border:hover a.es-button, .es-button-border:hover button.es-button { background:#FFFFFF;}body { width:100%; height:100%;}table { border-collapse:collapse; border-spacing:0px;}table td, body, .es-wrapper { padding:0; Margin:0;}.es-content, .es-header, .es-footer { width:100%; table-layout:fixed;}p, hr { Margin:0;}h1, h2, h3, h4, h5, h6 { Margin:0; font-family:arial, "helvetica neue", helvetica, sans-serif; letter-spacing:0;}.es-left { float:left;}.es-right { float:right;}.es-menu td { border:0;}s { text-decoration:line-through;}
                    ul, ol { font-family:helvetica, "helvetica neue", arial, verdana, sans-serif; padding:0px 0px 0px 40px; margin-top:15px; margin-bottom:15px;}ul li { color:#666666;}ol li { color:#666666;}li { margin:0px 0px 15px; font-size:16px;}a { text-decoration:none;}.es-menu td a { font-family:helvetica, "helvetica neue", arial, verdana, sans-serif; text-decoration:none; display:block;}.es-wrapper { width:100%; height:100%;}.es-wrapper-color, .es-wrapper { background-color:#FAFAFA;}.es-content-body p, .es-footer-body p, .es-header-body p, .es-infoblock p { font-family:helvetica, "helvetica neue", arial, verdana, sans-serif; line-height:150%; letter-spacing:0;}.es-header { background-color:transparent;}.es-header-body { background-color:#FFFFFF;}.es-header-body p { color:#333333; font-size:14px;}.es-header-body a { color:#1376C8; font-size:14px;}.es-footer { background-color:transparent;}.es-footer-body { background-color:transparent;}
                    .es-footer-body p { color:#333333; font-size:14px;}.es-footer-body a { color:#333333; font-size:14px;}.es-content-body { background-color:#FFFFFF;}.es-content-body p { color:#666666; font-size:16px;}.es-content-body a { color:#0B5394; font-size:16px;}.es-infoblock p { font-size:12px; color:#CCCCCC;}.es-infoblock a { font-size:12px; color:#CCCCCC;}h1 { font-size:20px; font-style:normal; font-weight:normal; line-height:120%; color:#333333;}h2 { font-size:14px; font-style:normal; font-weight:normal; line-height:120%; color:#333333;}h3 { font-size:20px; font-style:normal; font-weight:normal; line-height:120%; color:#333333;}h4 { font-size:24px; font-style:normal; font-weight:normal; line-height:120%; color:#333333;}h5 { font-size:20px; font-style:normal; font-weight:normal; line-height:120%; color:#333333;}h6 { font-size:16px; font-style:normal; font-weight:normal; line-height:120%; color:#333333;}
                    .es-header-body h1 a, .es-content-body h1 a, .es-footer-body h1 a { font-size:20px;}.es-header-body h2 a, .es-content-body h2 a, .es-footer-body h2 a { font-size:14px;}.es-header-body h3 a, .es-content-body h3 a, .es-footer-body h3 a { font-size:20px;}.es-header-body h4 a, .es-content-body h4 a, .es-footer-body h4 a { font-size:24px;}.es-header-body h5 a, .es-content-body h5 a, .es-footer-body h5 a { font-size:20px;}.es-header-body h6 a, .es-content-body h6 a, .es-footer-body h6 a { font-size:16px;}a.es-button, button.es-button { padding:15px 20px 15px 20px; display:inline-block; background:#FFFFFF; border-radius:10px 10px 10px 10px; font-size:14px; font-family:arial, "helvetica neue", helvetica, sans-serif; font-weight:bold; font-style:normal; line-height:120%; color:#3D5CA3; text-decoration:none; width:auto; text-align:center; letter-spacing:0;}
                    .es-button-border { border-style:solid; border-color:#3D5CA3 #3D5CA3 #3D5CA3 #3D5CA3; background:#FFFFFF; border-width:2px 2px 2px 2px; display:inline-block; border-radius:10px 10px 10px 10px; width:auto;}.es-button img { display:inline-block; vertical-align:middle;}.es-fw, .es-fw .es-button { display:block;}.es-il, .es-il .es-button { display:inline-block;}.es-text-rtl h1, .es-text-rtl h2, .es-text-rtl h3, .es-text-rtl h4, .es-text-rtl h5, .es-text-rtl h6, .es-text-rtl input, .es-text-rtl label, .es-text-rtl textarea, .es-text-rtl p, .es-text-rtl ol, .es-text-rtl ul, .es-text-rtl .es-menu a, .es-text-rtl .es-table { direction:rtl;}.es-text-ltr h1, .es-text-ltr h2, .es-text-ltr h3, .es-text-ltr h4, .es-text-ltr h5, .es-text-ltr h6, .es-text-ltr input, .es-text-ltr label, .es-text-ltr textarea, .es-text-ltr p, .es-text-ltr ol, .es-text-ltr ul, .es-text-ltr .es-menu a, .es-text-ltr .es-table { direction:ltr;}
                    .es-text-rtl ol, .es-text-rtl ul { padding:0px 40px 0px 0px;}.es-text-ltr ul, .es-text-ltr ol { padding:0px 0px 0px 40px;}.es-p10 { padding:10px;}.es-p20t { padding-top:20px;}.es-p20r { padding-right:20px;}.es-p20b { padding-bottom:20px;}.es-p20l { padding-left:20px;}.es-p40t { padding-top:40px;}.es-p5t { padding-top:5px;}.es-p5b { padding-bottom:5px;}.es-p15t { padding-top:15px;}.es-p15b { padding-bottom:15px;}.es-p40r { padding-right:40px;}.es-p40l { padding-left:40px;}.es-p35r { padding-right:35px;}.es-p25t { padding-top:25px;}.es-p10r { padding-right:10px;}.es-p40b { padding-bottom:40px;}.es-p10l { padding-left:10px;}.es-p10t { padding-top:10px;}.es-p30b { padding-bottom:30px;}.es-p5r { padding-right:5px;}.es-p10b { padding-bottom:10px;}.es-p5l { padding-left:5px;}.es-p30t { padding-top:30px;}.es-p-default { padding-top:20px; padding-right:20px; padding-left:20px;}.es-menu amp-img, .es-button amp-img { vertical-align:middle;}
                    @media only screen and (max-width:600px) {td.es-m-p20b { padding-bottom:20px } td.es-m-p0l { padding-left:0px } .es-p-default { } *[class="gmail-fix"] { display:none } p, a { line-height:150% } h1, h1 a { line-height:120% } h2, h2 a { line-height:120% } h3, h3 a { line-height:120% } h4, h4 a { line-height:120% } h5, h5 a { line-height:120% } h6, h6 a { line-height:120% } .es-header-body p { } .es-content-body p { } .es-footer-body p { } .es-infoblock p { } h1 { font-size:20px; text-align:center } h2 { font-size:16px; text-align:left } h3 { font-size:20px; text-align:center } h4 { font-size:24px; text-align:left } h5 { font-size:20px; text-align:left } h6 { font-size:16px; text-align:left } .es-header-body h1 a, .es-content-body h1 a, .es-footer-body h1 a { font-size:20px } .es-header-body h2 a, .es-content-body h2 a, .es-footer-body h2 a { font-size:16px }
                    .es-header-body h3 a, .es-content-body h3 a, .es-footer-body h3 a { font-size:20px } .es-header-body h4 a, .es-content-body h4 a, .es-footer-body h4 a { font-size:24px } .es-header-body h5 a, .es-content-body h5 a, .es-footer-body h5 a { font-size:20px } .es-header-body h6 a, .es-content-body h6 a, .es-footer-body h6 a { font-size:16px } .es-menu td a { font-size:14px } .es-header-body p, .es-header-body a { font-size:10px } .es-content-body p, .es-content-body a { font-size:16px } .es-footer-body p, .es-footer-body a { font-size:12px } .es-infoblock p, .es-infoblock a { font-size:12px } .es-m-txt-c, .es-m-txt-c h1, .es-m-txt-c h2, .es-m-txt-c h3, .es-m-txt-c h4, .es-m-txt-c h5, .es-m-txt-c h6 { text-align:center } .es-m-txt-r, .es-m-txt-r h1, .es-m-txt-r h2, .es-m-txt-r h3, .es-m-txt-r h4, .es-m-txt-r h5, .es-m-txt-r h6 { text-align:right }
                    .es-m-txt-j, .es-m-txt-j h1, .es-m-txt-j h2, .es-m-txt-j h3, .es-m-txt-j h4, .es-m-txt-j h5, .es-m-txt-j h6 { text-align:justify } .es-m-txt-l, .es-m-txt-l h1, .es-m-txt-l h2, .es-m-txt-l h3, .es-m-txt-l h4, .es-m-txt-l h5, .es-m-txt-l h6 { text-align:left } .es-m-txt-r amp-img { float:right } .es-m-txt-c amp-img { margin:0 auto } .es-m-txt-l amp-img { float:left } .es-m-txt-r .rollover:hover .rollover-second, .es-m-txt-c .rollover:hover .rollover-second, .es-m-txt-l .rollover:hover .rollover-second { display:inline } .es-m-txt-r .rollover span, .es-m-txt-c .rollover span, .es-m-txt-l .rollover span { line-height:0; font-size:0; display:block } .es-spacer { display:inline-table } a.es-button, button.es-button { font-size:14px; padding:10px 20px 10px 20px; line-height:120% } a.es-button, button.es-button, .es-button-border { display:block } .es-m-fw, .es-m-fw.es-fw, .es-m-fw .es-button { display:block }
                    .es-m-il, .es-m-il .es-button, .es-social, .es-social td, .es-menu { display:inline-block } .es-adaptive table, .es-left, .es-right { width:100% } .es-content table, .es-header table, .es-footer table, .es-content, .es-footer, .es-header { width:100%; max-width:600px } .adapt-img { width:100%; height:auto } .es-mobile-hidden, .es-hidden { display:none } .es-desk-hidden { width:auto; overflow:visible; float:none; max-height:inherit; line-height:inherit } tr.es-desk-hidden { display:table-row } table.es-desk-hidden { display:table } td.es-desk-menu-hidden { display:table-cell } .es-menu td { width:1% } table.es-table-not-adapt, .esd-block-html table { width:auto } .h-auto { height:auto } h2 a { text-align:left } }</style>
                    </head><body class="body"><div dir="ltr" class="es-wrapper-color" lang="en"> <!--[if gte mso 9]><v:background xmlns:v="urn:schemas-microsoft-com:vml" fill="t"> <v:fill type="tile" color="#fafafa"></v:fill> </v:background><![endif]--><table width="100%" cellspacing="0" cellpadding="0" class="es-wrapper"><tr><td valign="top"><table cellpadding="0" cellspacing="0" align="center" class="es-content"><tr><td align="center" class="es-adaptive"><table width="600" cellspacing="0" cellpadding="0" bgcolor="#ffffff" align="center" class="es-content-body" style="background-color:transparent"><tr><td align="left" class="es-p10"><table width="100%" cellspacing="0" cellpadding="0"><tr><td width="580" valign="top" align="center"><table width="100%" cellspacing="0" cellpadding="0"><tr><td align="center" class="es-infoblock"><p>Put your preheader text here. <a href="https://viewstripo.email" target="_blank" class="view">View in browser</a></p></td></tr>
                    </table></td></tr></table> </td></tr></table></td></tr></table> <table cellpadding="0" cellspacing="0" align="center" class="es-header"><tr><td align="center" class="es-adaptive"><table width="600" cellspacing="0" cellpadding="0" bgcolor="#3d5ca3" align="center" class="es-header-body" style="background-color:#3d5ca3"><tr><td bgcolor="#dddee2" align="left" class="es-p20t es-p20b es-p20r es-p20l" style="background-color:#dddee2"> <!--[if mso]><table width="560" cellpadding="0" cellspacing="0"><tr><td width="57" valign="top"><![endif]--><table cellspacing="0" cellpadding="0" align="left" class="es-left"><tr><td width="57" align="left" class="es-m-p20b"><table width="100%" cellspacing="0" cellpadding="0"><tr>
                    <td align="left" class="es-m-p0l" style="font-size:0px"><a href="https://nandi-maps.xyz" target="_blank"><amp-img src="https://ernvdcj.stripocdn.email/content/guids/11525ecc-c3de-4fdc-9d9e-8f180af77b29/images/androidchrome512x512.png" alt="nandi-find anything" width="57" title="nandi-find anything" class="adapt-img" style="display:block" height="57" layout="responsive"></amp-img></a> </td></tr></table></td></tr></table> <!--[if mso]></td><td width="5"></td><td width="498" valign="top"><![endif]--><table cellspacing="0" cellpadding="0" align="right" class="es-right"><tr><td width="498" align="left"><table width="100%" cellspacing="0" cellpadding="0"><tr><td align="left"><p style="font-size:22px;font-family:'noticia text', georgia, 'times new roman', serif"><strong>Nandi</strong></p><p style="font-family:arial, 'helvetica neue', helvetica, sans-serif">Find Anything</p></td></tr></table></td></tr></table> <!--[if mso]></td></tr></table>
                    <![endif]--></td></tr></table></td></tr></table> <table cellspacing="0" cellpadding="0" align="center" class="es-content"><tr><td bgcolor="#fafafa" align="center" style="background-color:#fafafa"><table width="600" cellspacing="0" cellpadding="0" bgcolor="#ffffff" align="center" class="es-content-body" style="background-color:#ffffff"><tr><td bgcolor="transparent" align="left" class="es-p40t es-p20r es-p20l" style="background-color:transparent;background-position:left top"><table width="100%" cellspacing="0" cellpadding="0"><tr><td width="560" valign="top" align="center"><table width="100%" cellspacing="0" cellpadding="0" style="background-position:left top"><tr><td align="center" class="es-p5t es-p5b" style="font-size:0"><amp-img src="https://ernvdcj.stripocdn.email/content/guids/CABINET_dd354a98a803b60e2f0411e893c82f56/images/23891556799905703.png" alt="" width="175" style="display:block" height="208"></amp-img></td></tr> <tr>
                    <td align="center" class="es-p15t es-p15b"><h1 style="color:#333333;font-size:20px"><strong>FORGOT YOUR </strong></h1><h1 style="color:#333333;font-size:20px"><strong>&nbsp;PASSWORD?</strong></h1></td></tr><tr><td align="center" class="es-p40r es-p40l"><p>HI,&nbsp;${user.firstName} ${user.lastName}</p></td></tr><tr><td align="left" class="es-p35r es-p40l"><p style="text-align:center">There was a request to change your password!</p></td></tr><tr><td align="center" class="es-p25t es-p40r es-p40l"><p>If did not make this request, just ignore this email. Otherwise, please click the button below to change your password:</p></td></tr><tr><td align="center" class="es-p40t es-p40b es-p10r es-p10l"><span class="es-button-border"><a href="${url}" target="_blank" class="es-button">RESET PASSWORD</a></span></td></tr></table></td></tr></table></td></tr> <tr>
                    <td align="left" class="es-p5t es-p20b es-p20r es-p20l" style="background-position:left top"><table width="100%" cellspacing="0" cellpadding="0"><tr><td width="560" valign="top" align="center"><table width="100%" cellspacing="0" cellpadding="0"><tr><td align="center"><p style="font-size:14px">Contact us: +6285641889512 | um1684694<a target="_blank" href="mailto:your@mail.com" style="font-size:14px;color:#666666">@gmail.com</a></p></td></tr></table></td></tr></table></td></tr></table></td></tr></table> <table cellspacing="0" cellpadding="0" align="center" class="es-footer"><tr><td bgcolor="#fafafa" align="center" style="background-color:#fafafa"><table width="600" cellspacing="0" cellpadding="0" bgcolor="#ffffff" align="center" class="es-footer-body"><tr>
                    <td bgcolor="#0b5394" align="left" class="es-p10t es-p30b es-p20r es-p20l" style="background-color:#0b5394;background-position:left top"><table width="100%" cellspacing="0" cellpadding="0"><tr><td width="560" valign="top" align="center"><table width="100%" cellspacing="0" cellpadding="0"><tr><td align="left" class="es-p5t es-p5b"><h2 style="font-size:16px;color:#ffffff"><strong>Have quastions?</strong></h2></td></tr><tr><td align="left" class="es-p5b"><p style="font-size:14px;color:#ffffff">We are here to help, learn more about us <a target="_blank" style="font-size:14px;color:#ffffff;text-decoration:none">here</a></p> <p style="font-size:14px;color:#ffffff">or <a target="_blank" style="font-size:14px;text-decoration:none;color:#ffffff">contact us</a><br></p></td></tr></table></td></tr></table></td></tr></table></td></tr></table> <table cellspacing="0" cellpadding="0" align="center" class="es-content"><tr>
                    <td bgcolor="#fafafa" align="center" style="background-color:#fafafa"><table width="600" cellspacing="0" cellpadding="0" bgcolor="transparent" align="center" class="es-content-body" style="background-color:transparent"><tr><td align="left" class="es-p15t" style="background-position:left top"><table width="100%" cellspacing="0" cellpadding="0"><tr><td width="600" valign="top" align="center"><table width="100%" cellspacing="0" cellpadding="0"><tr><td><table width="100%" cellspacing="0" cellpadding="0" class="es-menu"><tr class="links"><td id="esd-menu-id-0" width="100%" valign="top" bgcolor="transparent" align="center" class="es-p10t es-p10b es-p5r es-p5l" style="padding-bottom:1px;padding-top:0px"><a target="_blank" href="https://nandi-maps.xyz/register" style="color:#3D5CA3;font-size:14px">Sign up</a></td> </tr></table></td></tr><tr>
                    <td align="center" class="es-p20b es-p20r es-p20l" style="font-size:0"><table width="100%" cellspacing="0" cellpadding="0" border="0"><tr><td style="border-bottom:1px solid #fafafa;background:none;height:1px;width:100%;margin:0px"></td></tr></table></td></tr></table></td></tr></table></td></tr></table></td></tr></table> <table cellspacing="0" cellpadding="0" align="center" class="es-footer"><tr><td bgcolor="#fafafa" align="center" style="background-color:#fafafa"><table width="600" cellspacing="0" cellpadding="0" bgcolor="transparent" align="center" class="es-footer-body" style="background-color:transparent"><tr><td align="left" class="es-p15t es-p5b es-p20r es-p20l"><table width="100%" cellspacing="0" cellpadding="0"><tr><td width="560" valign="top" align="center"><table width="100%" cellspacing="0" cellpadding="0"><tr>
                    <td align="center"><p style="font-size:12px;color:#666666">This daily newsletter was sent to info@name.com from company name because you subscribed. If you would not like to receive this email <a target="_blank" class="unsubscribe" style="font-size:12px;text-decoration:underline">unsubscribe here</a>.</p></td></tr></table></td></tr></table></td></tr></table> </td></tr></table><table cellspacing="0" cellpadding="0" align="center" class="es-content"><tr><td align="center"><table width="600" cellspacing="0" cellpadding="0" bgcolor="#ffffff" align="center" class="es-content-body" style="background-color:transparent"><tr><td align="left" class="es-p30t es-p30b es-p20r es-p20l"><table width="100%" cellspacing="0" cellpadding="0"><tr><td width="560" valign="top" align="center"><table width="100%" cellspacing="0" cellpadding="0"><tr>
                    <td align="center" class="es-infoblock made_with" style="font-size:0"><a target="_blank" href="https://viewstripo.email/?utm_source=templates&utm_medium=email&utm_campaign=education&utm_content=trigger_newsletter2"><amp-img src="https://ernvdcj.stripocdn.email/content/guids/cab_pub_7cbbc409ec990f19c78c75bd1e06f215/images/78411525331495932.png" alt="" width="125" style="display:block" height="56"></amp-img></a></td> </tr></table></td></tr></table></td></tr></table></td></tr></table></td></tr></table></div></body></html>`;

    await this.mailerService.sendMail({
      from: '"Nandi Maps" <admin@nandi-maps.xyz>',
      to: user.email,
      subject: 'Reset Password',
      html: bodyEmail,
    });
  }
}
